var Const={URI_MAX_LEN:1800,NL:"\r\n"},Capability={TRANSLATE:1,DETECT_LANGUAGE:2,LISTEN:4,DICTIONARY:8},HttpMethod={UNDEFINED:0,GET:1,POST:2},CodePage={WINDOWS1251:1251,UTF8:65001,ISO8859_1:28591};function ServiceHeader(a,b,c,e){this.id=a;this.name=b||"";this.info=c||"";this.capabilities=e}
function RequestData(a,b,c,e,d,f){this.method=a;this.uri=b||"";this.data=c||"";this.headers=e||(a==HttpMethod.UNDEFINED?"":a==HttpMethod.GET?getHeader():postHeader());this.codepage=d||CodePage.UTF8;this.responseHandler=f||""}function ResponseData(a,b,c,e,d){this.translation=a||"";this.sourceLanguage=b;this.translationLanguage=c;this.data=e||"";this.nextRequestHandler=d||""}var Options={LanguageCode:"en",LanguageFirst:"en"};
function initializeOptions(a,b){Options.LanguageCode=a;Options.LanguageFirst=b}function addOption(a,b){Options[a]=b}function getHeader(){var a=format("Accept-Language: {0};q=0.8,en-US;q=0.6,en;q=0.4",Options.LanguageCode);return"Accept: */*"+Const.NL+a+Const.NL+"Accept-Encoding: gzip,deflate"+Const.NL+"Accept-Charset: utf-8"}function postHeader(){return getHeader()+Const.NL+"Content-Type: application/x-www-form-urlencoded; charset=utf-8"}
function encodeUriParam(a){return a?encodeURIComponent(a):""}function encodeGetParam(a){a=encodeUriParam(a);if(a.length>Const.URI_MAX_LEN){a=a.slice(0,Const.URI_MAX_LEN);var b=a.lastIndexOf("%20");if(0<b)return a.slice(0,b)}return a}function encodePostParam(a){return encodeUriParam(a)}function format(){for(var a=arguments[0],b=0;b<arguments.length-1;b++)a=a.replace(new RegExp("\\{"+b+"\\}","gm"),arguments[b+1]);return a}
function midString(a,b,c,e){if(!a)return"";var d=a.indexOf(b);if(-1!==d){var f=a.indexOf(c,d+b.length);if(f>d)return e?f+=c.length:d+=b.length,a.slice(d,f)}return""}function leftString(a,b,c){if(!a)return"";if(b&&a.length>b&&(a=a.slice(0,b),c))for(b=a.length-1;0<=b;b--){var e=a.charAt(b);if(-1!==c.indexOf(e))return a.slice(0,b)}return a}function trimString(a){return a?a.replace(/(^\s+)|(\s+$)/g,""):""}
function unquoteHtml(a){if(!a)return"";a=a.replace(/&amp[;]?/g,"&");a=a.replace(/&lt[;]?/g,"<");a=a.replace(/&gt[;]?/g,">");a=a.replace(/&quot[;]?/g,'"');return a=a.replace(/&#[0]?39[;]/g,"'")}function removeEmptyLines(a){if(!a)return"";a=a.replace(/\r/gi,"");a=a.split("\n");for(var b=0;b<a.length;b++)a[b].match(/[\S]/g)||(a[b]="");a=a.join("\n").replace(/\n{3,}/g,"\n\n");a=a.replace(/\n/gi,Const.NL);return trimString(a)}
function stripHtml(a){if(!a)return"";a=a.replace(/<(style|script)(.|\s)*?(style|script)>/g,"");a=a.replace(/<br\/>/gi,Const.NL);a=a.replace(/<[^>]+>/g,"");a=a.replace(/&nbsp;/g," ");return removeEmptyLines(a)}function regExpRemove(a,b,c){if(!b)return a;b=format(c,b.join("|"));return a.replace(new RegExp(b,"g"),"")}function removeAttributes(a,b){return regExpRemove(a,b," ({0})(?:s*=s*(?:(?:\"((?:\\.|[^\"])*)\")|(?:'((?:\\.|[^'])*)')|([^>s]+)))?")}
function removeTags(a,b){return regExpRemove(a,b,"</?({0})[^>]*>")}function removeElements(a,b){return regExpRemove(a,b,"<s*({0})[^>]*>((.|\n)*?)<s*/s*({0})>")}
function updateHtmlLinks(a,b){if(!a)return"";a=a.replace(/href="\/\//gi,'href="http://');a=a.replace(/href="\//gi,'href="http://'+b+"/");a=a.replace(/src="\/\//gi,'src="http://');a=a.replace(/src="\//gi,'src="http://'+b+"/");a=a.replace(/href='\/\//gi,"href='http://");a=a.replace(/href='\//gi,"href='http://"+b+"/");a=a.replace(/src='\/\//gi,"src='http://");return a=a.replace(/src='\//gi,"src='http://"+b+"/")}
var SupportedLanguages=null,UNKNOWN_LANGUAGE_CODE=-1,UNKNOWN_LANGUAGE=0,AUTO_DETECT_LANGUAGE=1,ENGLISH_LANGUAGE=17;function isLanguage(a){return a>AUTO_DETECT_LANGUAGE&&a<SupportedLanguages.length}function codeFromLanguage(a){return a==AUTO_DETECT_LANGUAGE||isLanguage(a)?SupportedLanguages[a]:UNKNOWN_LANGUAGE_CODE}
function languageFromCode(a){if(SupportedLanguages[ENGLISH_LANGUAGE]==a)return ENGLISH_LANGUAGE;for(var b=AUTO_DETECT_LANGUAGE;b<SupportedLanguages.length;b++)if(SupportedLanguages[b]==a)return b;return UNKNOWN_LANGUAGE}function usesAutoDetectCode(){return SupportedLanguages[AUTO_DETECT_LANGUAGE]!==UNKNOWN_LANGUAGE_CODE};
